name: CD - Main Branch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build project
        run: mvn clean package -DskipTests

      - name: Deploy to Server
        shell: bash
        run: |
          echo "배포 시작..."
          # scp target/routy-back.jar ubuntu@your-server:/app/routy-back/
          # ssh ubuntu@your-server "sudo systemctl restart routy.service"
          echo "배포 완료 ✅"