name: CD - Main Branch

on:
    push:
        branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest
        env:
            DB_USERNAME: ${{ secrets.DB_USERNAME }}
            DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
            TNS_ADMIN_PATH: ${{ secrets.TNS_ADMIN_PATH }}

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-java@v4
              with:
                  distribution: 'temurin'
                  java-version: '21'

            - uses: actions/cache@v4
              with:
                  path: ~/.m2
                  key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
                  restore-keys: |
                      ${{ runner.os }}-maven-

            - name: Build project
              run: mvn clean package -DskipTests
